query getLabSemester($id: ID!) {
	getLabSemester(id: $id) {
		id
		semesterName
		description
		professor
		monitorEmailList
		studentEmailList
		laboratoryID
		updatedAt
		updatedBy
		createdBy
		createdAt
		_version
		_deleted
		_lastChangedAt
	}
}
