query getLabPractice($id: ID!) {
	getLabPractice(id: $id) {
		id
		name
		description
		duration
		guideS3Path
		_version
		LabPracticeSessions {
			items {
				id
			}
		}
		Laboratory {
		  id
		}
	}
}
