query getLabPracticeSession($id: ID!) {
	getLabPracticeSession(id: $id) {
		id
		videoUrlCode
		endDate
		description
		leaderUsers
		_deleted
		labpracticeID
		startDate
		labSemesterID
		_version
	}
}