query getUserLabPractices {
	listUserLabPracticeSessions {
		items {
			id
			sessionEndDate
			sessionStartDate
			LabPracticeSession {
				endDate
				startDate
				LabPractice {
					id
					name
					description
				}
			}
		}
	}
}
