query listLabPracticeCommands ($id: ID!) {
	listLabPracticeCommands(filter: {labpracticeID : {eq:$id}}) {
		items {
			id
			name
			description
			labelName
			labpracticeID
			_version
			_deleted
			LabPracticeParameters {
				items {
					id
					name
					description
					labelName
					defaultValue
					maxValue
					minValue
					regex
					_version
					_deleted
				}
			}
		}
	}
}
