query listLabPracticeSessionCommands($id: ID!) {
	listLabPracticeSessionCommands(filter: {labpracticesessionID: {eq: $id}}) {
		items {
			id
			status
			parameters
			LabPracticeCommand {
				id
				name
			}
			executionDate
			requestDate
			labpracticecommandID
			labpracticesessionID
		}
	}
}
