query listUserLabSemestersByUserId($userID: ID!) {
	listUserLabSemesters(filter: {userID: {eq: $userID}}) {
		items {
			id
			userID
			labsemester {
				id
				description
				professor
				monitorEmailList
				studentEmailList
				semesterName
				Laboratory {
					id
					name
				}
				_version
				_deleted
			}
			_version
			_deleted
		}
	}
}
