query listUserLabSemestersByUserId($userID: ID!) {
	listUserLabSemesters(filter: {userID: {eq: $userID}}) {
		items {
			id
			userID
			labsemester {
				id
				semesterName
				description
				Laboratory {
					id
					name
				}
				updatedAt
				updatedBy
				createdBy
				createdAt
				_lastChangedAt
				_deleted
				_version
			}
			_version
			_deleted
		}
	}
}
