query listUserLabPracticeSessions($id: ID!) {
	listUserLabPracticeSessions(filter: {userID : {eq:$id}}) {
		items {
			id
			sessionEndDate
			sessionStartDate
			_version
			_deleted
			LabPracticeSession {
				id
				startDate
				endDate
				description
				_version
				_deleted
				LabSemester {
					id
					semesterName
					description
				}
				LabPractice {
				  id
				  name
				  description
				  duration
					_deleted
				  Laboratory {
					  id
					  name
					  description
				  }
				  LabPracticeDeviceId
				}
			}
		}
	}
}
