query listLaboratoriesByUser {
	listUserLabSemesters(filter: {userID: {eq: "16295a0d-7ea0-4452-95a1-7e45068f4191"}}) {
		items {
			labsemester {
				Laboratory {
					id
					name
				}
			}
		}
	}
}
