query listLabPracticeCommands ($id: ID!) {
	listLabPracticeCommands(filter: {labpracticeID : {eq:$id}}) {
		items {
			id
			name
			labelName
			labpracticeID
			LabPracticeParameters {
				items {
					id
					name
					labelName
					defaultValue
				}
			}
		}
	}
}
