query listLabPracticeSessionCommands {
	listLabPracticeSessionCommands {
		items {
			id
			status
			parameters
			LabPracticeCommand {
				id
				name
			}
			executionDate
			requestDate
			labpracticecommandID
			labpracticesessionID
		}
	}
}
