query listUserLabSemestersByUserId($userID: ID!) {
	listUserLabSemesters(filter: {userID: {eq: $userID}}) {
		items {
			id
			user {
				id
				name
				email
				role
				_deleted
			}
			labsemester {
				id
				semesterName
			}
			_version
			_deleted
		}
	}
}
