query listUserLabPracticeSessions($id: ID!) {
	listUserLabPracticeSessions(filter: {userID : {eq:$id}}) {
		items {
			id
			sessionEndDate
			sessionStartDate
			LabPracticeSession {
				id
				startDate
				endDate
				LabPractice {
				  id
				  name
				  description
				  duration
				  Laboratory {
					  id
					  name
					  description
				  }
				  LabPracticeDevice {
					 id
				  }
				}
			}
		}
	}
}
