/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://suyo76f525grpph3owjsbkoepa.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-2lwzqnmamjfwbnownxgqur6sgy",
    "aws_cognito_identity_pool_id": "us-east-2:6331e38d-a076-4349-98b5-81ab3e82d98b",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_sYVFylt3P",
    "aws_user_pools_web_client_id": "4ueiacku7rk8118029vddmktur",
    "oauth": {
        "domain": "unalvirtuallabsd9e2ffd9-d9e2ffd9-develop.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
		//"redirectSignIn": "https://d1p0lxk2wvxo6e.cloudfront.net/",
        //"redirectSignOut": "https://d1p0lxk2wvxo6e.cloudfront.net/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "unal-labs-files-dev222622-develop",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
