query getUserLabPracticeSession($id: ID!) {
	getUserLabPracticeSession(id: $id) {
		userID
		LabPracticeSession {
			startDate
			endDate
         description
			LabPractice {
				name
            description
			}
		}
	}
}
