service: unal-labs

frameworkVersion: "3"

# plugins:
  # - serverless-webpack
  # - serverless-bundle

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 256
  stage: ${opt:stage, "dev"}
  region: "us-east-2"
  environment:
    GRAPHQL_ENDPOINT: ${self:custom.graphqlEndpoint.${self:provider.stage}}
    API_KEY: ${self:custom.apiKey.${self:provider.stage}}
  # iamRoleStatements:
  #   - Effect: "Allow"
  #     Action:
  #       - iot:*
  #     Resource: "*"

functions:
  - ${file(resources/functions/Functions.yml)}

resources:
  - ${file(resources/storage/FrontendBucket.yml)}

custom:
  bucketName: unal-virtual-labs-${self:provider.stage}
  graphqlEndpoint:
    dev: https://5c4xkk3c55htnl7os5hvar7n34.appsync-api.us-east-2.amazonaws.com/graphql
  apiKey:
    dev: da2-s77v3vheprg7npaifa324bdrmq