query getLabPracticeCommand {
   listLabPracticeCommands {
      items {
         id
         name
         LabPracticeParameters {
            items{
               id
               name 
               defaultValue
            }
         }
      }
   }
}