query getLabPracticeCommand {
	listLabPracticeCommands {
		items {
			id
			name
			labelName
			labpracticeID
			LabPracticeParameters {
				items {
					id
					name
					labelName
					defaultValue
				}
			}
		}
	}
}
