mutation updateLabPracticeSessionCommand($input: CreateLabPracticeSessionCommandInput!) {
	createLabPracticeSessionCommand(input: $input) {
		id
		labpracticesessionID
		labpracticecommandID
		status
		parameters
	}
}
