/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const appSyncConfig = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://4xgfahcqmvfmti2gv2rfwhflxe.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nujzzwmwo5hftcmaj7axynomui"
};


module.exports = appSyncConfig;
//export default appSyncConfig;