query getLabCommandsList ($LabPracticeParametersId: ID!) {
   getLabPracticeCommand(id: $LabPracticeParametersId) {
      name
      description
      LabPracticeParameters {
         items {
            name
            description
            defaultValue
            defaultValue
            minValue
            maxValue
            regex
         }
      }
   }
}