query getLabPracticeOutput {
	getLabPracticeOutput(id: 1) {
		id
		name
		descriptio
		units
		updatedBy
		createdBy
		LabPracticeSessionOutputs {
			items {
				value
			}
			nextToken
			startedAt
		}
	}
}