subscription onUpdateLabPracticeSessionCommandBySessionID($id: ID!) {
	onUpdateLabPracticeSessionCommandBySessionID(labpracticesessionID: $id) {
		id
		executionDate
		status
		LabPracticeCommand {
			id
			name
		}
		parameters
		labpracticesessionID
		labpracticecommandID
	}
}
