subscription onUpdateLabPracticeSessionCommandBySessionID($id: ID!) {
	onUpdateLabPracticeSessionCommandBySessionID(labpracticesessionID: $id) {
		id
		labpracticecommandID
		labpracticesessionID
		status
	}
}
